version: "3.0"
services:
  jetson-gpu:
    build: .
    image: gputest
    devices:
      - "/dev/nvhost-ctrl"
      - "/dev/nvhost-ctrl-gpu"
      - "/dev/nvhost-prof-gpu"
      - "/dev/nvmap"
      - "/dev/nvhost-gpu"
      - "/dev/nvhost-as-gpu"
    volumes:  
      - "/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra"
    

